server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: user-management
          uri: lb://USER-MANAGEMENT
          predicates:
            - Path=/api/v1/users/**

        - id: student-management
          uri: lb://STUDENT-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/students/**,/api/v1/student-enrollments/**

        - id: academic-management
          uri: lb://ACADEMIC-MANAGEMENT
          predicates:
            - Path=/api/v1/academic/**

        - id: faculty-management
          uri: lb://FACULTY-MANAGEMENT
          predicates:
            - Path=/api/v1/teachers/**,/api/v1/teacher-assignments/**

        - id: attendance-management
          uri: lb://ATTENDANCE-MANAGEMENT
          predicates:
            - Path=/api/v1/attendance/**

        - id: examination-management
          uri: lb://EXAMINATION-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/examination/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              - http://localhost:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
jwt:
  secret: 4eab74d923edcecae9839fb51a6b4b2d0b5d748b73d9421af74d6f7a8d7c3e9f
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO