server:
  port: 8084

spring:
  application:
    name: ACADEMIC-MANAGEMENT

  datasource:
    url: jdbc:mysql://localhost:3306/academic_x?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"